# Generated by Django 3.2.4 on 2021-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
